# Generated by Django 4.1.5 on 2023-01-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentType', models.CharField(max_length=4)),
                ('documentNumber', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(blank=True, max_length=50, null=True)),
                ('lastName', models.CharField(max_length=100)),
                ('hobbie', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'unique_together': {('documentType', 'documentNumber')},
            },
        ),
    ]
